spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  show-sql: true

spring.datasource:
  hikari.maxium-pool-size: 4
  url: jdbc:postgresql://ec2-3-208-74-199.compute-1.amazonaws.com/d4jqckjdq9po17
  username: elvqzflyayucuh
  password: 1e5f3616f90462c162720469b5b4abc726dd1fcb10fbe5251f626d6d00a8c75f
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: project.sns-application-2023.secret_key
  # 30 days
  token.expired-time-ms: 2592000000