spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  show-sql: true

spring.datasource:
  hikari.maxium-pool-size: 4
  url: jdbc:postgresql://ec2-52-0-79-72.compute-1.amazonaws.com/d4v0et7cfio63h
  username: kjsslgpffbmyab
  password: 946042b25c6b8c09040116bac9e7a2bb391b528bd31a77a7010906e852a7cc84
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: project.sns-application-2023.secret_key
  # 30 days
  token.expired-time-ms: 2592000000