spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  show-sql: true

spring.datasource:
  hikari.maxium-pool-size: 4
  url: jdbc:postgresql://ec2-3-208-74-199.compute-1.amazonaws.com
  username: utgdrvrfkfmzwh
  password: d754642d99148bfcab80cc3965b0078aa8fd807a37d5dcdf033fa4d9161f1bb0
  platform: postgres
  driver-class-name: org.postgresql.Driver
